---
- name: Get Total Disk in GB only    
  #calculation is wrong if there's a disk with MB
  shell: fdisk -l|grep /dev/sd > disk
  args:
    executable: /bin/bash
    
- shell: awk '/Disk \/dev\/sd/ {print $3}' disk  > disk2
  args:
    executable: /bin/bash

- shell: cat disk2 | wc -l
  args:
    executable: /bin/bash
  register: countline

#- name:  show value
#  debug: msg="{{ countline.stdout }}"

- name: if count = 1  
  shell: cat disk2 > /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: countline.stdout == '1'
  
- name: if count = 2
  shell: awk '{sum+=$1} (NR%2)==0{print sum}' disk2 > /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: countline.stdout == '2'
  
- name: if count = 3
  shell: awk '{sum+=$1} (NR%2)==0{print sum}' disk2 > /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: countline.stdout == '3'
  
- name: if count = 4
  shell: awk '{sum+=$1} (NR%4)==0{print sum}' disk2 > /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: countline.stdout == '4'
