---
- name: Get Total Disk in GB only    
  #calculation is wrong if there's a disk with MB
  shell: fdisk -l|grep /dev/sd > disk
  args:
    executable: /bin/bash
    
- shell: awk '/Disk \/dev\/sd/ {print $3}' disk  > disk2
  args:
    executable: /bin/bash

- shell: disk2 | wc -l
  args:
    executable: /bin/bash
  register: value

- name:  show value
  debug: msg="{{ value.stdout }}"

- name: if count > 1  
  shell: awk '{sum+=$1} (NR%3)==0{print sum}' disk2 >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: value.stdout > 1
  
- name: if count = 1  
  shell: cat disk >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash 
  when: value..stdout = 1
  
