---

- name: Get hostname
  shell: hostname > /tmp/{{ ansible_hostname }}_data.csv
  #no_log: true
  args:
    executable: /bin/bash

- name: Get hostname
  shell: hostname -I | cut -d' ' -f1 >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash

- name: Get cpu core
  shell: nproc >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash

- shell: awk '/MemTotal/ {print $2}' /proc/meminfo > memory
  args:
    executable: /bin/bash

- name: Get memory in GB
  shell: awk '{ print $1/1000000}' memory >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash

- name: Get Total Disk in GB only    
  #calculation is wrong if there's a disk with MB
  shell: fdisk -l|grep /dev/sd > disk
  args:
    executable: /bin/bash
 
- shell: awk '/Disk \/dev\/sd/ {print $3}' disk  > disk2
  args:
    executable: /bin/bash
    
- shell: awk '{sum+=$1} (NR%3)==0{print sum}' disk2 >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash

- name: Put CSV Header output.csv
  shell: echo 'Hostname,IP,CPU-core,Ram,Disk,' > /tmp/{{ ansible_hostname }}_output.csv
  args:
    executable: /bin/bash

- name: Put it in CSV in one line
  shell: cat /tmp/{{ ansible_hostname }}_data.csv | awk '{print}' ORS=','  >> /tmp/{{ ansible_hostname }}_output.csv
  args:
    executable: /bin/bash
    
   


 
