---

- name: Get hostname
  shell: hostname > /tmp/{{ ansible_hostname }}_data.csv
  #no_log: true
  args:
    executable: /bin/bash
   
- name: Get cpu core
  shell: nproc >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash

- name: Get memory
  shell: awk '/MemTotal/ {print $2}' /proc/meminfo >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash
  
- name: Get Disk    
  shell: fdisk -l|grep /dev/sd > disk
  args:
    executable: /bin/bash
 

- shell: awk '/Disk \/dev\/sd/ {print $3}' disk  >> /tmp/{{ ansible_hostname }}_data.csv
  args:
    executable: /bin/bash


 
