---

- shell: hostname > /tmp/{{ ansible_hostname }}info.csv
  #no_log: true
  args:
    executable: /bin/bash

- name: Get hostname  
  debug:
    var: result
    verbosity: 2
   
- shell: echo CPU core 
  args:
    executable: /bin/bash
  
- name: Get cpu core
  shell: nproc 
  args:
    executable: /bin/bash

- shell: echo Memory 
  args:
    executable: /bin/bash

- name: Get memory
  shell: awk '/MemTotal/ {print $2}' /proc/meminfo 
  args:
    executable: /bin/bash
  
- shell: echo Disk
  args:
    executable: /bin/bash

- name: Get Disk    
  shell: fdisk -l|grep /dev/sd > disk
  args:
    executable: /bin/bash
 

- shell: awk '/Disk \/dev\/sd/ {print $3}' disk
  args:
    executable: /bin/bash


 
