---
- firewalld:
    service: https
    permanent: true
    state: enabled
- firewalld:
    service: http
    permanent: true
    state: enabled     
- name: Bounce firewalld
  service: name=firewalld state=restarted    
    
