---

- name: Fetching file
  fetch:
    src: /tmp/{{ ansible_hostname }}_output.csv
    dest: /tmp/fetched

- name: Delete file first
  file:
    path: /tmp/main_output.csv
    state: absent
  ignore_errors: True

- name: Combined to one file
  shell: cat /tmp/fetched/{{ ansible_hostname }}/tmp/{{ ansible_hostname }}_output.csv >> /tmp/main_output.csv && printf '\r\n' >> /tmp/main_output.csv
  args:
    executable: /bin/bash
  delegate_to: localhost
